FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements/base.txt /app/requirements/base.txt
RUN pip install --no-cache-dir -r /app/requirements/base.txt

COPY . /app

EXPOSE 8000

CMD ["uvicorn", "fastapi_app.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
